SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
  FROM REST_INFO I
   JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
          FROM REST_INFO 
          GROUP BY FOOD_TYPE) MAX_I
    ON I.FOOD_TYPE = MAX_I.FOOD_TYPE
    AND I.FAVORITES = MAX_I.FAVORITES
  ORDER BY I.FOOD_TYPE DESC