SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
  FROM PATIENT P
   JOIN APPOINTMENT A
   ON P.PT_NO = A.PT_NO
   JOIN DOCTOR D
   ON D.DR_ID = A.MDDR_ID
  WHERE TO_CHAR(A.APNT_YMD, 'YYYYMMDD') = '20220413'
   AND D.MCDP_CD = 'CS'
   AND APNT_CNCL_YN = 'N'
  ORDER BY APNT_YMD