SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, PRODUCT_NAME
  FROM FOOD_PRODUCT FP 
        JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
                FROM FOOD_PRODUCT
                 WHERE CATEGORY IN ('과자','국','김치','식용유')
                GROUP BY CATEGORY) MAX_FP 
        ON FP.CATEGORY = MAX_FP.CATEGORY 
        AND FP.PRICE = MAX_FP.MAX_PRICE
  ORDER BY MAX_PRICE DESC;